version: "3.8"
services:
  postgres:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      env_file:
        - postgres.env
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      restart: always