# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: ./aplicacao
        run: docker-compose up -d 
      - name: Testes
        working-directory: ./aplicacao
        run: docker exec app bash -c "rails db:reset; rspec"
      - name: Lint
        working-directory: ./aplicacao
        run: docker exec app bash -c "gem install rubocop; rubocop -A --fail-level F"
